---
- name: Configure Windows 2016 DC Settings
  hosts: all
  gather_facts: no
  vars:
    ansible_user: Administrator
    domain_name: hax.local

  tasks:
    - name:  create new Schema options
      win_shell: | 
        $adSchema = (Get-ADRootDSE).schemaNamingContext
        $userSchema = Get-ADObject -SearchBase $adSchema -Filter "Name -eq 'User'"
        $Prefix = "1.2.840.113556.1.8000.2554"
        $GUID = [System.Guid]::NewGuid().ToString()
        $GUIDPart = @()
        $GUIDPart += [UInt64]::Parse($GUID.SubString(0,4), "AllowHexSpecifier")
        $GUIDPart += [UInt64]::Parse($GUID.SubString(4,4), "AllowHexSpecifier")
        $GUIDPart += [UInt64]::Parse($GUID.SubString(9,4), "AllowHexSpecifier")
        $GUIDPart += [UInt64]::Parse($GUID.SubString(14,4), "AllowHexSpecifier")
        $GUIDPart += [UInt64]::Parse($GUID.SubString(19,4), "AllowHexSpecifier")
        $GUIDPart += [UInt64]::Parse($GUID.SubString(24,6), "AllowHexSpecifier")
        $GUIDPart += [UInt64]::Parse($GUID.SubString(30,6), "AllowHexSpecifier")
        $OID = [String]::Format("{0}.{1}.{2}.{3}.{4}.{5}.{6}.{7}", $Prefix, $GUIDPart[0], $GUIDPart[1], $GUIDPart[2], $GUIDPart[3], $GUIDPart[4], $GUIDPart[5], $GUIDPart[6])
        $attributeName = "PrimaryWorkstation"
        $attributeDesc = "Primary Workstation Name"
        $oMSyntax = 64
        $attributeSyntax = "2.5.5.12"
        $indexable = 0
        $adAttributes = @{
          lDAPDisplayName = $attributeName;
          adminDescription = $attributeDesc;
          attributeId = $OID;
          oMSyntax = $oMSyntax;
          attributeSyntax = $attributeSyntax;
          searchflags = $indexable
        }
        New-ADObject -Name  $attributeName -Type attributeSchema -Path $adSchema -OtherAttributes $adAttributes
        $userSchema | Set-ADObject -Add @{mayContain = $attributeName}  
  
    - name:  create new users
      win_shell: | 
        $AccountPass = (Read-Host -AsSecureString '{{ user_password }}')
           1..1000 | %{$attrs = @{Name = "user00$($_)"; AccountPassword = $AccountPass; Enabled = $true; Path = "OU=Standard,OU=Users,OU=_HAX,DC=hax,DC=local"}; New-ADUser @attrs -OtherAttributes @{'mail'="user00$($_)@hax.local"}}
           1..50 | %{$attrs = @{Name = "priv_user00$($_)"; AccountPassword = $AccountPass; Enabled = $true; Path = "OU=Human,OU=Privileged,OU=Users,OU=_HAX,DC=hax,DC=local"}; New-ADUser @attrs -OtherAttributes @{'mail'="priv_user00$($_)@hax.local"}}
           1..50 | %{$attrs = @{Name = "svc_acct00$($_)"; AccountPassword = $AccountPass; Enabled = $true; Path = "OU=Service,OU=Privileged,OU=Users,OU=_HAX,DC=hax,DC=local"}; New-ADUser @attrs}
  
